# Generated by Django 4.0.3 on 2022-03-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_artikel_isi'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
