# Generated by Django 4.0.3 on 2022-03-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_artikel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
